[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "public/auditor/index.html"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/auditor"
  to = "/auditor/index.html"
  status = 200
