[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/auditor"
  to = "/auditor/index.html"
  status = 200

[[redirects]]
  from = "/screens/:screen"
  to = "/screens/:screen.html"
  status = 200
